// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: FanControl

#ifndef _FANCONTROL_UI_H
#define _FANCONTROL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_TempScreen
void ui_TempScreen_screen_init(void);
extern lv_obj_t *ui_TempScreen;
extern lv_obj_t *ui_PresetPanel;
extern lv_obj_t *ui_Label4;
void ui_event_Preset1Btn( lv_event_t * e);
extern lv_obj_t *ui_Preset1Btn;
extern lv_obj_t *ui_Label1;
void ui_event_Preset2Btn( lv_event_t * e);
extern lv_obj_t *ui_Preset2Btn;
extern lv_obj_t *ui_Label2;
void ui_event_Preset3Btn( lv_event_t * e);
extern lv_obj_t *ui_Preset3Btn;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_TempPanel;
extern lv_obj_t *ui_CurrentTempPanel;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_CurrentTempLabel;
extern lv_obj_t *ui_CurrentTemp;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_FanRPMLabel;
extern lv_obj_t *ui_FanRPM;
extern lv_obj_t *ui_FanRPMBar;
extern lv_obj_t *ui_TargetTempPanel;
void ui_event_TargetTempDnBtn( lv_event_t * e);
extern lv_obj_t *ui_TargetTempDnBtn;
extern lv_obj_t *ui_Label9;
void ui_event_TargetTempUpBtn( lv_event_t * e);
extern lv_obj_t *ui_TargetTempUpBtn;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_TargetTempLabel;
extern lv_obj_t *ui_TargetTemp;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
