// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: FanControl

#include "ui.h"

void targetTempDn(lv_event_t * e)
{
	// Your code here
}

void targetTempUp(lv_event_t * e)
{
	// Your code here
}
