// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: FanControl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void targetTempDn(lv_event_t * e);
void targetTempUp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
