// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: FanControl

#include "../ui.h"

void ui_TempScreen_screen_init(void)
{
ui_TempScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TempScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TempScreen, lv_color_hex(0x464646), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PresetPanel = lv_obj_create(ui_TempScreen);
lv_obj_set_width( ui_PresetPanel, lv_pct(33));
lv_obj_set_height( ui_PresetPanel, lv_pct(100));
lv_obj_set_x( ui_PresetPanel, 161 );
lv_obj_set_y( ui_PresetPanel, 0 );
lv_obj_set_align( ui_PresetPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PresetPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PresetPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PresetPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PresetPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PresetPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PresetPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_PresetPanel);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -2 );
lv_obj_set_y( ui_Label4, -89 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Presets");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Preset1Btn = lv_btn_create(ui_PresetPanel);
lv_obj_set_width( ui_Preset1Btn, 100);
lv_obj_set_height( ui_Preset1Btn, 50);
lv_obj_set_x( ui_Preset1Btn, -130 );
lv_obj_set_y( ui_Preset1Btn, -27 );
lv_obj_set_align( ui_Preset1Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Preset1Btn,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Preset1Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Preset1Btn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Preset1Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Preset1Btn, lv_color_hex(0xFFC8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Preset1Btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Preset1Btn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Preset1Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Preset1Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Preset1Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Preset1Btn, 2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label1 = lv_label_create(ui_Preset1Btn);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 160 );
lv_obj_set_y( ui_Label1, -23 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"PLA");

ui_Preset2Btn = lv_btn_create(ui_PresetPanel);
lv_obj_set_width( ui_Preset2Btn, 100);
lv_obj_set_height( ui_Preset2Btn, 50);
lv_obj_set_x( ui_Preset2Btn, 159 );
lv_obj_set_y( ui_Preset2Btn, -24 );
lv_obj_set_align( ui_Preset2Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Preset2Btn,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Preset2Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Preset2Btn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Preset2Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Preset2Btn, lv_color_hex(0xFFC8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Preset2Btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Preset2Btn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Preset2Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Preset2Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Preset2Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Preset2Btn, 2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label2 = lv_label_create(ui_Preset2Btn);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 158 );
lv_obj_set_y( ui_Label2, 45 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"PETG");

ui_Preset3Btn = lv_btn_create(ui_PresetPanel);
lv_obj_set_width( ui_Preset3Btn, 100);
lv_obj_set_height( ui_Preset3Btn, 50);
lv_obj_set_x( ui_Preset3Btn, 161 );
lv_obj_set_y( ui_Preset3Btn, 108 );
lv_obj_set_align( ui_Preset3Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Preset3Btn,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Preset3Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Preset3Btn, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Preset3Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Preset3Btn, lv_color_hex(0xFFC8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Preset3Btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Preset3Btn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Preset3Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Preset3Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Preset3Btn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Preset3Btn, 2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_Label3 = lv_label_create(ui_Preset3Btn);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 160 );
lv_obj_set_y( ui_Label3, 107 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"ABS");

ui_TempPanel = lv_obj_create(ui_TempScreen);
lv_obj_set_width( ui_TempPanel, lv_pct(66));
lv_obj_set_height( ui_TempPanel, lv_pct(100));
lv_obj_set_x( ui_TempPanel, -78 );
lv_obj_set_y( ui_TempPanel, 0 );
lv_obj_set_align( ui_TempPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TempPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_TempPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_TempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TempPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurrentTempPanel = lv_obj_create(ui_TempPanel);
lv_obj_set_width( ui_CurrentTempPanel, 300);
lv_obj_set_height( ui_CurrentTempPanel, 128);
lv_obj_set_x( ui_CurrentTempPanel, -73 );
lv_obj_set_y( ui_CurrentTempPanel, -68 );
lv_obj_set_align( ui_CurrentTempPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_CurrentTempPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_CurrentTempPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_CurrentTempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CurrentTempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CurrentTempPanel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_CurrentTempPanel);
lv_obj_set_width( ui_Panel5, 155);
lv_obj_set_height( ui_Panel5, 80);
lv_obj_set_x( ui_Panel5, -50 );
lv_obj_set_y( ui_Panel5, 3 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CurrentTempLabel = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_CurrentTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CurrentTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CurrentTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CurrentTempLabel,"Current Temp");

ui_CurrentTemp = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_CurrentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CurrentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CurrentTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_CurrentTemp,"28 C");
lv_obj_set_style_text_font(ui_CurrentTemp, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_CurrentTempPanel);
lv_obj_set_width( ui_Panel6, 100);
lv_obj_set_height( ui_Panel6, 80);
lv_obj_set_x( ui_Panel6, -10 );
lv_obj_set_y( ui_Panel6, -70 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_FanRPMLabel = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_FanRPMLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FanRPMLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FanRPMLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_FanRPMLabel,"Fan RPM");

ui_FanRPM = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_FanRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FanRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_FanRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_FanRPM,"3000");

ui_FanRPMBar = lv_bar_create(ui_Panel6);
lv_bar_set_value(ui_FanRPMBar,25,LV_ANIM_OFF);
lv_obj_set_width( ui_FanRPMBar, 53);
lv_obj_set_height( ui_FanRPMBar, 10);
lv_obj_set_x( ui_FanRPMBar, -33 );
lv_obj_set_y( ui_FanRPMBar, 3 );
lv_obj_set_align( ui_FanRPMBar, LV_ALIGN_CENTER );

ui_TargetTempPanel = lv_obj_create(ui_TempPanel);
lv_obj_set_width( ui_TargetTempPanel, 302);
lv_obj_set_height( ui_TargetTempPanel, 134);
lv_obj_set_x( ui_TargetTempPanel, -72 );
lv_obj_set_y( ui_TargetTempPanel, 77 );
lv_obj_set_align( ui_TargetTempPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TargetTempPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TargetTempPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TargetTempPanel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTempDnBtn = lv_btn_create(ui_TargetTempPanel);
lv_obj_set_width( ui_TargetTempDnBtn, 100);
lv_obj_set_height( ui_TargetTempDnBtn, 50);
lv_obj_set_x( ui_TargetTempDnBtn, 87 );
lv_obj_set_y( ui_TargetTempDnBtn, 30 );
lv_obj_set_align( ui_TargetTempDnBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TargetTempDnBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TargetTempDnBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_TargetTempDnBtn);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"DOWN");

ui_TargetTempUpBtn = lv_btn_create(ui_TargetTempPanel);
lv_obj_set_width( ui_TargetTempUpBtn, 100);
lv_obj_set_height( ui_TargetTempUpBtn, 50);
lv_obj_set_x( ui_TargetTempUpBtn, 87 );
lv_obj_set_y( ui_TargetTempUpBtn, -29 );
lv_obj_set_align( ui_TargetTempUpBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TargetTempUpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TargetTempUpBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_TargetTempUpBtn);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"UP");

ui_Panel4 = lv_obj_create(ui_TargetTempPanel);
lv_obj_set_width( ui_Panel4, 155);
lv_obj_set_height( ui_Panel4, 80);
lv_obj_set_x( ui_Panel4, -54 );
lv_obj_set_y( ui_Panel4, 3 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TargetTempLabel = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_TargetTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TargetTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TargetTempLabel,"Target Temp");

ui_TargetTemp = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_TargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TargetTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_TargetTemp,"30 C");
lv_obj_set_style_text_font(ui_TargetTemp, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Preset1Btn, ui_event_Preset1Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Preset2Btn, ui_event_Preset2Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Preset3Btn, ui_event_Preset3Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TargetTempDnBtn, ui_event_TargetTempDnBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TargetTempUpBtn, ui_event_TargetTempUpBtn, LV_EVENT_ALL, NULL);

}
